config/routes.rb
Rails.application.routes.draw do
  

 
  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]
  end
   resources :posts, only: [] do
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end
  resources :users, only: [:new,:create, :show]
  get 'about' => 'welcome#about'
  
 resources :sessions, only: [:new, :create, :destroy]

  root to: 'welcome#index'
  
   namespace :api do
     namespace :v1 do
       resources :users, only: [:index, :show, :create, :update]
       resources :topics, except: [:edit, :new] do
            resources :posts, only: [:create]
       end
           
       resources :posts, only: [:index, :show, :update, :destroy]
       resources :comments, only: [:index, :show]
     end
   end
  
  
  
  
  

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post
  
  
  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true
 
private
 
 def update_post
   post.update_rank
 end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    before_action :require_sign_in
    respond_to :html, :js

def up_vote
    @post = Post.find(params[:post_id])
    @vote = update_vote(1)
   
   

 
end
   
def down_vote
    @post = Post.find(params[:post_id])
    @vote = update_vote(-1)
 

end
 

   private
   
   def update_vote(new_value)
     @post = Post.find(params[:post_id])
     @vote = @post.votes.where(user_id: current_user.id).first
 
     if @vote
       @vote.update_attribute(:value, new_value)
     else
       @vote = current_user.votes.create(value: new_value, post: @post)
     end
   end
   
   
   
   
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_voter.html.erb
<% if current_user %>

<div class="pull-left vote-arrows">
   <div><%= link_to " ", post_up_vote_path(post), class: 'glyphicon glyphicon-chevron-up', method: :post, remote: true%></div>
   <strong>
      <%= content_tag :div, id: "post_voteCount-#{post.id}" do %>
         <%= post.points %>
      <% end %>
   </strong>
   <div><%= link_to " ", post_down_vote_path(post), class: 'glyphicon glyphicon-chevron-down', method: :post, remote: true %></div>
 </div>
 
 <% end %>

app/views/votes/down_vote.js.erb
<% if @vote == true %>
    $('#post_voteCount-'+<%= @post.id %> ).html("<%= @post.points %>")
<% end %>

app/views/votes/up_vote.js.erb
<% if @vote == true %>
$('#post_voteCount-'+<%= @post.id %>).html("<%= @post.points %>")
<% end %>